## 1. O que é NumPy?

In [ ]:
# Biblioteca para trabalhar com arrays numéricos.

### Lista Python ---> lenta / básica
### NumPy array ---> rápido / matemático

## 2. Import padrão

In [4]:
import numpy as np #esta é a convenção aplicada no mercado

# Exercícios

## 1. Criando array

In [2]:
import numpy as np

dados = np.array([10, 20, 30])
print(dados)

[10 20 30]


## 2. Operações

In [4]:
print(dados * 2)
print(dados + 10)

[20 40 60]
[20 30 40]


## 3. Média

In [6]:
print(dados.mean())

20.0


## 4. Engenharia - Sensores

In [7]:
import numpy as np

freq = np.array([100, 200, 300])

media = freq.mean()

print("Média:", media)

Média: 200.0


# 5. Mini desafio
### Coletar dados
### Transformar em array
### Calcular média automaticamente

In [ ]:
import numpy as np
import math as m
import random as rd

#def mediafreq(freq):
#        soma = 0
#        for i in freq:
#            soma += i
#        return soma / len(freq)

while True:
    freq = []
    
    for valor in range(5):
        
        while True:
            try:
                valor = float(input("Digite o valor da frequencia (Hz): "))
                ruido = rd.uniform(-0.5, 0.5)
                valor_real = valor + ruido
                freq.append(valor_real)
                break
            except ValueError:
                print("Digite apenas números!")
                
    freq_array = np.array(freq)
       
    media = freq_array.mean()
    
    print(freq)
    print(media)
    
    if media > 250:
        print("CRÍTICO")
    elif media > 150:
        print("ALERTA")
    else:
        print("SISTEMA OPERANTE")
    
    STOP = input("Deseja parar? (S/N): ").strip().upper()
    
    if STOP == "S" or STOP == "SIM":
        break
    else:
        print("Continuando")

Digite o valor da frequencia (Hz): 100
Digite o valor da frequencia (Hz): 200
Digite o valor da frequencia (Hz): 300
Digite o valor da frequencia (Hz): 400
Digite o valor da frequencia (Hz): 500
[100.27235770832655, 199.87115428477347, 300.2300958168853, 399.94137763196517, 500.0006330241217]
300.06312369321444
CRÍTICO
