## 1. Array multidimensionais

In [4]:
import numpy as np

# Matriz 2D

dados = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Acessando elementos | (x = linhas; y = colunas) | começando sempre de 0 (zero). 

print(dados[0, 0]) #10
print(dados[1, 2]) #60

10
60


## 2. Estatísticas importantes

In [6]:
print(dados.mean()) # media geral
print(dados.max()) # máximo
print(dados.min()) # mínimo

35.0
60
10


## 3. Operações por eixo

In [7]:
# Axis:
# 0 ==== colunas
# 1 ==== linhas

print(dados.mean(axis = 0)) # media por colunas
print(dados.mean(axis = 1)) # media por linhas

[25. 35. 45.]
[20. 50.]


## 4. Filtros (lógica vetorial)

In [8]:
dados = np.array([10, 50, 100, 200])

print(dados > 80)

[False False  True  True]


In [9]:
print(dados[dados > 80])

[100 200]


## 5. Operações vetoriais reais

In [11]:
dados = np.array([1, 2, 3])

resultado = dados * 10 + 5

print(resultado)

[15 25 35]


# Exercícios

## 1. Matriz

In [12]:
import numpy as np

dados = np.array([
    [100, 200],
    [300,400]
])

print(dados)

[[100 200]
 [300 400]]


## 2. Estatísticas

In [15]:
print(dados.mean())
print(dados.max())

250.0
400


## 3. Axis

In [17]:
print(dados.mean(axis = 0))
print(dados.mean(axis = 1))

[200. 300.]
[150. 350.]


## 4. Filtro - engenharia

In [19]:
freq = np.array([100, 200, 300, 400])

crit = freq[freq > 250]

print(crit)

[300 400]


# 5. Mini desafio
### Matriz = sensores x tempo
### Calcular média por sensor
### Detectar falhas

In [24]:
import numpy as np

# 6 sensores, 3 medições

dados = np.array([
    [10, 20, 30], # sensor 1
    [40, 50, 60], # sensor 2
    [70, 80 ,90], # sensor 3
    [100, 110, 120], # sensor 4
    [130, 140, 150], # sensor 5
    [160, 170, 180] # sensor 6
])

med_sens = dados.mean(axis = 1)

print("Média: ", med_sens)

falha = dados[dados > 150]

print("Sensores com falha: ", falha)

Média:  [ 20.  50.  80. 110. 140. 170.]
Sensores com falha:  [160 170 180]
